### ISSUE TITLE
No such module 'GoogleMaps'

### ISSUE THREAD

**Issue by michaelbina** [EurekaCommunity/GooglePlacesRow#1]
I'm having problems integrating this library and it all seems to revolve around the GoogleMaps framework.

When I follow the directions in the README, I immediately get a compile error on 'import GoogleMaps' in AppDelegate which says:

```
No such module 'GoogleMaps'
```

If I add 'import GooglePlacesRow' before the 'import GoogleMaps', the compile error goes away, but then I get the following error on build:

```
ld: framework not found GoogleMaps for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried forking the library and adding the library as a dependency in the podspec, but that caused a lot of other errors.  

I even tried running the Example Xcode project in the repo and am also seeing "No such module 'GoogleMaps'" there and am not able to run it.

Not sure how this works for anyone else, but please let me know if you think you can help out with this...

**Comment by mats-claassen** [comment]
Hey @michaelbina , did you follow [the example instructions](https://github.com/EurekaCommunity/GooglePlacesRow#examples)?

That should work. The important step here is that you must download GoogleMaps framework and copy it to the `Frameworks` folder at the root of your project

The only step not documented there is that you also have to copy the `Eureka.framework` to the `Frameworks` folder (as with all carthage installed frameworks)

**Comment by michaelbina** [comment]
Just tried this with the file shared in the example instructions you sent and there are errors.

<img width="1018" alt="screen shot 2016-05-02 at 2 48 36 pm" src="https://cloud.githubusercontent.com/assets/528845/14969070/2903b92a-1075-11e6-9bc0-809501dc0d1f.png">

When I had originally tried just adding GoogleMaps to my pod file, it was complaining about a duplicate dependency, I'm assuming because your framework already includes it as a static framework.  Have you also tried adding it as a dependency in the podspec and getting things to work that way?  It would be much cleaner and make this much easier to install.

**Comment by mats-claassen** [comment]
In fact I tried that yes but as GoogleMaps is a ObjectiveC framework with a static binary, Cocoapods will complain if it is added as dependency.
I am not sure this is the perfect solution but it worked for me installing it in a empty project.
I did not test it tough in a project that is already set up and depends on other pods / frameworks although I think problems could only arrive when you are using some of the libraries this pod includes.

In your case its more like your project has GoogleMaps but lacks some of its dependencies like ImageIO or GLKit which by the way are declared as dependencies

**Comment by lognaturel** [comment]
I got the same results when trying to create a new project and install through Cocoapods. I didn't do much troubleshooting because I wanted to use the suggestion functionality independent of GooglePlaces. 

Not sure where to ask/suggest this but it might be helpful to have that simplified "suggestion row" made available. I could share what I have although I'd like some quick feedback on the best way to make it as general as possible.

**Comment by mats-claassen** [comment]
I had not thought about a more generic "Suggestion row" but I think it is a great idea. You would have to create a good protocol so that anyone can change from where the suggestions come.

It would also free us of all these problems with external static binaries as dependencies and the user would have to include those.

@lognaturel if you want to create such a row, I can give you access and you create a new repository in EurekaCommunity.

**Comment by lognaturel** [comment]
Can do! I added `var filterFunction: ((String) -> [String])!` to `SuggestionRowProtocol` and set `filterFunction` when adding the row. That works well for my purposes but I'm sure there's a more flexible way that also doesn't require the implicitly unwrapped optional. What's the best way to discuss that?  I suppose I could add what I have to the new repo and we could iterate there?

**Comment by mats-claassen** [comment]
Yes let us continue there.

**Comment by mats-claassen** [comment]
GoogleMapsBase and GooglePlaces come as vendored frameworks now so they do not have to be downloaded and setting the `Framework search path` Build Setting as mentioned in [the installation section of the Readme](https://github.com/EurekaCommunity/GooglePlacesRow#installation) should work.
