### ISSUE TITLE
Once I have a GooglePlacesTableRow working, how do I access the GMSPlace data for my autocomplete result?

### ISSUE THREAD

**Issue by GenghisTheKhan** [EurekaCommunity/GooglePlacesRow#10]
Hello, I would like to access the properties of the GMSPlace that my user selects from the autocomplete results; specifically I'm trying to access the name and CLLocationCoordinate2D of the place. Thank You.

**Comment by GenghisTheKhan** [comment]
Hello, I would like to access the properties of the GMSPlace that my user selects from the autocomplete results; specifically I'm trying to access the name and CLLocationCoordinate2D of the place.  Thank You.

**Comment by mats-claassen** [comment]
The value of the row holds that information (`row.value`).

The value is a `GooglePlace` which can hold user input or a `GMSAutocompletePrediction`
