### ISSUE TITLE
Cocoapods update

### ISSUE THREAD

**Issue by dneykov** [EurekaCommunity/GooglePlacesRow#13]
I saw that Eureka 3.0.0 support is added but the pod is not updated.
Can you please update the pod. I want to update my project with Eureka 3.0.0

Thanks.

**Comment by ijaureguialzo** [comment]
Hi @dneykov, in Github it's already updated but not published to CocoaPods. 

You can use a direct reference to Github in your podfile to force the latest release:

`pod 'GooglePlacesRow', :git => 'https://github.com/EurekaCommunity/GooglePlacesRow.git'`

Hope it helps.

**Comment by dneykov** [comment]
Hi @ijaureguialzo,
Thanks for the advice.
