### ISSUE TITLE
How do I extract the string from a GooglePlaces.prediction?

### ISSUE THREAD

**Issue by lookatitude** [EurekaCommunity/GooglePlacesRow#19]
I managed to build a form, and use googlePlacesRows in several fields, works fine for me until I get the values from the entire form.

when I do from.values() to get all values from the form and assign its values to a model, for the GooglePlacesRow I get a GooglePlaces object instead of the string shown on the field like so:
Optional(PROJECT.GooglePlace.prediction(GMSAutocompletePrediction 0x7fb836c85c50: "Lisbon, Portugal", id: ChIJO_PkYRozGQ0R0DaQ5L3rAAQ, types: (
    locality,
    political,
    geocode
)))]

how can I extract the String value of this object?
Maybe a basic question so sorry for posting this under issues.

**Comment by andorfermichael** [comment]
@lookatitude you closed the issue, so I suppose you found a solution, didn't you? How do access the values now? I am having the same troubles and I would appreciate your help.

**Comment by allenhuang** [comment]
I use the following code to get the input text:
It would be more convenient if GooglePlace can provide a method or property to return input text as String.

```swift
var city: String
if let place = form.values()["City"] as? GooglePlace {
  switch place {
  case let GooglePlace.userInput(val):
      city = val
  case let GooglePlace.prediction(pred):
      city = pred.attributedPrimaryText.string
  }
}
```
