### ISSUE TITLE
Codesigning error with GoogleMaps

### ISSUE THREAD

**Issue by maa-x** [EurekaCommunity/GooglePlacesRow#2]
When building with Cocoapods (I added the framework search path), I get a codesigning error: `Frameworks/GoogleMaps.framework: bundle format unrecognized, invalid, or unsuitable`

I have tried cleaning the project and deleting the derived data, to no avail.

**Comment by mats-claassen** [comment]
Hi @SASDOE thanks for using this. This did not happen to me so I can just guess. I suppose you have already looked at Stackoverflow answers, but did you check [this answer](http://stackoverflow.com/a/18149893/4708657)?

**Comment by mats-claassen** [comment]
Has anyone else had this error?
