### ISSUE TITLE
Breaks with Eureka Swift 4: "requires Eureka 3.0.0"

### ISSUE THREAD

**Issue by thorng** [EurekaCommunity/GooglePlacesRow#21]
Could you update the pod so that it works with Eureka's new Swift 4 update?

**Comment by dylankbuckley** [comment]
+1 on this.

**Comment by elevins** [comment]
@dylankbuckley  any luck on this?

**Comment by uknowmeright** [comment]
Same Issue. Is this repo dead?

**Comment by dneykov** [comment]
Any plans for migration to Eureka 4.0

**Comment by mats-claassen** [comment]
Hi all, I was away for a while. Will try to get this working again

**Comment by mats-claassen** [comment]
There is a Pull request in #22. You can try if it works for you using the branch `swift4`
