### ISSUE TITLE
No such module 'GoogleMaps'

### ISSUE THREAD

**Issue by antonijap** [EurekaCommunity/GooglePlacesRow#24]
When I try to use `GoogleMaps` in AppDelegate file I get this error. I tried clearing project, shutting down Xcode but nothing helps. Any ideas?

**Comment by silvinaroldan** [comment]
I had the same error. I fixed it this way:
<img width="773" alt="googlemaps" src="https://user-images.githubusercontent.com/8246422/37926652-3d8d0b1a-310e-11e8-92e8-852e853ba462.png">
As in the example project

**Comment by antonijap** [comment]
Yeah. I figured it just a minute ago. I am forking this and writing proper documentation. Hopefully, nobody else will lose time in figuring this 🙄

**Comment by mats-claassen** [comment]
Fixed with #25
