### ISSUE TITLE
Getting value out of a row

### ISSUE THREAD

**Issue by antonijap** [EurekaCommunity/GooglePlacesRow#26]
I might be missing something super clear but when I use `row.value` I get this:

```
prediction(GMSAutocompletePrediction 0x60000024f3f0: "City, Country", id: ChIJkQYhlscLkkYRY_fiO4S9Ts0, types: (
    locality,
    political,
    geocode
))
```

I see in source code `GooglePlace` is an enum but I have zero clues how to extract city and country out of this.

**Comment by mats-claassen** [comment]
`GMSAutocompletePrediction` is defined in GooglePlaces. You can look at their documentation but here are a few properties of that class:

`attributedFullText` is the whole prediction String.
`attributedPrimaryText` is the first part and
`attributedSecondaryText` is the second part.

Example:

Full: **Sydney Opera House, Sydney, New South Wales, Australia**
First part: *Sydney Opera House*
Second part: *Sydney, New South Wales, Australia*
