### ISSUE TITLE
Use of unresolved identifier 'GMSServices';

### ISSUE THREAD

**Issue by fefereliezer** [EurekaCommunity/GooglePlacesRow#32]
iv'e tried bridging and it still doesn't work

**Comment by mats-claassen** [comment]
I think `GMSServices` is included in GoogleMaps while this library only includes GoolgePlaces and GoogleMapsBase frameworks.
You would have to install GoogleMaps separately.

Or use `GMSPlacesClient`

**Comment by fefereliezer** [comment]
Thanks for commenting,
but this is what the instructions are.


```
How to use GooglePlacesRow
First, navigate to AppDelegate.swift and add import GooglePlaces on top.

// AppDelegate.swift
import GooglePlaces
In method didFinishLaunchingWithOptions add this code before return keyword.

// AppDelegate.swift, application:didFinishLaunchingWithOptions
let apiKey = "YOUR_API_KEY"
GMSServices.provideAPIKey(apiKey)
```

As you can see, it instructs to use `GMSService`

but i'll try `GMSPlacesClient` and let you know if it worked.

i actually tried installing GoogleMaps separately but pod install gave me errors of conflicting files.

**Comment by mats-claassen** [comment]
Sorry, the Readme is wrong: You should use `GMSPlacesClient.provideAPIKey(apiKey)`
