### ISSUE TITLE
An internal error occurred in the Places API library

### ISSUE THREAD

**Issue by sarbogast** [EurekaCommunity/GooglePlacesRow#36]
I'm using this amazing component in my Eureka form and up until yesterday afternoon, it worked like a charm. And then since yesterday evening, without having changed anything, I started receiving these error messages:

> The operation couldn’t be completed. An internal error occurred in the Places API library. If you believe this error represents a bug, please file a report using the instructions on our community and support page (https://developers.google.com/places/ios-sdk/support).

I double checked my API key, it's loaded and I didn't exceed the quota or anything. I tried removing app and API restrictions but it didn't change anything. At this stage, I'm down to either a problem with Google's API responses or really a bug in the library. But given the way you depend on it in your podspec, I'm not sure if I can update the GooglePlaces library.

What's your take on what the problem might be?

**Comment by sarbogast** [comment]
I'm starting to wonder if this might not be related with this series of messages I have in the logs when my application runs. I have similar messages for all the classes loaded by GooglePlacesRow:

> objc[9015]: Class GMSPlacesClient is implemented in both 
> /Users/sarbogast/Library/Developer/CoreSimulator/Devices/8719F126-E5E4-4D6E-A6B9-F38FE1B95F93/data/Containers/Bundle/Application/7327962E-3C6E-4B7A-BEE6-9A4B380A091A/NomadFlare.app/Frameworks/GooglePlacesRow.framework/GooglePlacesRow (0x1092c8710) and 
> /Users/sarbogast/Library/Developer/CoreSimulator/Devices/8719F126-E5E4-4D6E-A6B9-F38FE1B95F93/data/Containers/Bundle/Application/7327962E-3C6E-4B7A-BEE6-9A4B380A091A/NomadFlare.app/NomadFlare (0x104b2df80). One of the two will be used. Which one is undefined.

And I'm thinking that if there are 2 instances of GMSPlacesClient in the environment, maybe I'm providing my API key to one and the other is getting used and it doesn't see the provider key.
Any idea why I might have duplicate classes like that?

**Comment by sarbogast** [comment]
Bingo! FYI, this was the cause of the issue: https://github.com/CocoaPods/CocoaPods/issues/7155
After a CocoaPods upgrade, the GooglePlacesRow library was linked twice.
With the workaround, it works. But I hope they fix this issue pretty quick.

**Comment by mats-claassen** [comment]
Great that you found a workaround.
I am not too convinced about the way we depend on GooglePlaces in this pod but back in the time when it was implemented it seemed to be the only way. Ideally we would add GooglePlaces as a dependency and not include its framework.

**Comment by sarbogast** [comment]
Which should be possible now since there is an official GooglePlaces pod: https://cocoapods.org/pods/GooglePlaces

**Comment by mats-claassen** [comment]
The problem was not that there was no pod but that they build a static library which couldn't be a Cocoapods dependency of another pod (transitive dependency)

**Comment by dairan** [comment]
Hi, I am facing same problem. I solved it removing  use_frameworks! from Podfile
Is there other way?
