### ISSUE TITLE
Places API?

### ISSUE THREAD

**Issue by michaelbina** [EurekaCommunity/GooglePlacesRow#4]
I'm wondering if this library would be possible without including the entire GoogleMaps api which comes in at over 125MB.  I would think that all that is needed is the Places API which I imagine is much smaller.  Has this been looked into for this?

**Comment by mats-claassen** [comment]
Yeah that is completely true. The fact is that GoogleMaps is one big framework and is not submodularized. At least I did not find anything else.
[Here](https://developers.google.com/places/ios-api/start#step-3-install-the-api-using-cocoapods) is the guide how to use the Places API

**Comment by mats-claassen** [comment]
I have now seen that Google split Places API from Google Maps. Will try to update this code to use that API if possible

**Comment by mats-claassen** [comment]
Updated in version 1.0.0
