### ISSUE TITLE
Swift3 compatibility?

### ISSUE THREAD

**Issue by chriscohoat** [EurekaCommunity/GooglePlacesRow#5]
Thanks for the great library! Unfortunately using the new Swift3 branch of Eureka there are a number of build failures. Do you expect to update this custom row to support the newer version of Eureka?

**Comment by mats-claassen** [comment]
Yes definitely. But we have to release a version of Eureka with Swift 3 first. This is because a pod cannot depend on a branch of another one but has to depend on a tag/release

**Comment by bentacles** [comment]
A Eureka release for swift 3 is now available https://github.com/xmartlabs/Eureka/releases/tag/2.0.0-beta.1

**Comment by mats-claassen** [comment]
@chriscohoat @bentacles master branch is now compatible with Swift 3. I want it to be tested a bit before releasing.

**Comment by chriscohoat** [comment]
Thanks a bunch @mats-claassen ... I'll be taking a look this afternoon.

**Comment by nuclearghost** [comment]
@mats-claassen plans to make a release with Swift 3 compatibility?

**Comment by mats-claassen** [comment]
Done
