### ISSUE TITLE
GoogleMapsBase is not a dylib // GooglePlaces is not a dylib

### ISSUE THREAD

**Issue by calvinorchiz** [EurekaCommunity/GooglePlacesRow#8]
Xcode 8.2.1
Swift 3

I'm integrating GooglePlacesRow as described in the installation description:
- pod 'GooglePlacesRow'
- $(PROJECT_DIR)/Pods/GooglePlacesRow/Frameworks to the Build Settings/Framework Search Paths

The table, cells and rows are forking fine, but still i get the following two warnings:
Auto-Linking supplied ... /Pods/GooglePlacesRow/Frameworks/GoogleMapsBase.framework/GoogleMapsBase is not a dylib

Auto-Linking supplied ...
/Pods/GooglePlacesRow/Frameworks/GooglePlaces.framework/GooglePlaces is not a dylib

btw .. i love the Eureka Framework. It's so easy and powerful to build professional tables 👍

**Comment by mats-claassen** [comment]
I do see this warning as well. Will try to have a look at it when I have some time. Seems to be working, however.

**Comment by ijaureguialzo** [comment]
I've tried rebuilding the pod with Google's SDK as dependency, removing the manually added frameworks and it doesn't work. It gives errors about transitive dependencies not being resolved.

It seems that we are stuck until Google releases a new pod that is not statically compiled, and there's not timeline for it. 

See [this issue](https://github.com/googlemaps/google-maps-ios-utils/issues/23) for more info.

**Comment by ijaureguialzo** [comment]
It seems that Google is moving on this. Not quite sure if it's enough yet: http://cocoapods.org/pods/GooglePlaces#changelog

**Comment by mats-claassen** [comment]
Seems GooglePlaces is still a static binary so it is still not working.
It would be great if that changes and we can add it as a dependency.

**Comment by annjawn** [comment]
I am noticing a whole bunch of errors in the Sample code.

**Comment by ijaureguialzo** [comment]
@annjawn, you should be more specific about which errors are you noticing so we can help.

For example, which version of Xcode are you using?

**Comment by ijaureguialzo** [comment]
It seems this issue is now solved in release 3.0.0.

Tested in Xcode 9.2.

**Comment by mats-claassen** [comment]
Nice. I guess we can close this then
